# Generated by Django 4.2.6 on 2023-10-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='creator',
            field=models.CharField(max_length=100, null=True, verbose_name='укажите автора'),
        ),
    ]
