# Generated by Django 4.2.6 on 2023-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cinema_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание фильма'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='вставьте постер фильма'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='название фильма'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='type_film',
            field=models.CharField(choices=[('хоррор', 'хоррор'), ('фантастика', 'фантастика'), ('приключения', 'приключения'), ('боевик', 'боевик')], max_length=100, null=True, verbose_name='каддите жанр'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='year',
            field=models.DateField(null=True, verbose_name='дата созадния:'),
        ),
    ]
