# Generated by Django 4.2.6 on 2023-10-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_cinema_description_alter_cinema_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
