# Generated by Django 4.2.6 on 2023-10-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cinema_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='image',
        ),
    ]
